# Generated by Django 5.1.4 on 2025-01-19 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("material", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={"verbose_name": "Курс", "verbose_name_plural": "Курсы"},
        ),
        migrations.AlterModelOptions(
            name="lesson",
            options={"verbose_name": "Урок", "verbose_name_plural": "Уроки"},
        ),
        migrations.AlterField(
            model_name="course",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="course",
            name="preview",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="materials/course_previews/",
                verbose_name="Превью",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="title",
            field=models.CharField(
                max_length=200, unique=True, verbose_name="Название"
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="preview",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="materials/lesson_previews/",
                verbose_name="Превью",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="title",
            field=models.CharField(
                max_length=200, unique=True, verbose_name="Название"
            ),
        ),
    ]
