# Generated by Django 5.1.4 on 2025-01-31 14:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("material", "0004_subscription"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subscription",
            options={"verbose_name": "Подписка", "verbose_name_plural": "Подписки"},
        ),
        migrations.AlterUniqueTogether(
            name="subscription",
            unique_together={("user", "course")},
        ),
        migrations.AddField(
            model_name="course",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Цена",
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Цена",
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="lesson",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscriptions",
                to="material.lesson",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscriptions",
                to="material.course",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="subscription",
            unique_together={("user", "course"), ("user", "lesson")},
        ),
    ]
